export const COMPOSITE_IDS_URL = `${process.env.REACT_APP_API_URL}/server/rest/secured/data/comp/identifiers?group=&server=`;
export const COMPOSITE_LAST_URL = `${process.env.REACT_APP_API_URL}/server/rest/secured/logout`;
export const SINGLE_LAST_URL = `${process.env.REACT_APP_API_URL}/server/rest/secured/data/sing/last?group=&server=`;
export const SERVERS_URL = `${process.env.REACT_APP_API_URL}/server/rest/secured/server`;
export const DATA_GROUPS_URL = `${process.env.REACT_APP_API_URL}/server/rest/secured/group`;
export const LOGIN_URL = `${process.env.REACT_APP_API_URL}/server/rest/login`;
export const LOGOUT_URL = `${process.env.REACT_APP_API_URL}/server/rest/secured/logout`;
export const REGISTRATION_URL = `${process.env.REACT_APP_API_URL}/server/rest/registration`;
export const REFRESH_TOKENS_URL = `${process.env.REACT_APP_API_URL}/server/rest/secured/refresh-tokens`;
